export const MAINNET_INFURA = process.env.NEXT_PUBLIC_MAINNET_INFURA_API_KEY

export const ETHERSCAN_API_KEY = process.env.NEXT_PUBLIC_ETHERSCAN_API_KEY
export const POLYGON_ETHERSCAN_API_KEY = process.env.NEXT_PUBLIC_POLYGON_ETHERSCAN_API_KEY
export const AVAX_ETHERSCAN_API_KEY = process.env.NEXT_PUBLIC_AVAX_ETHERSCAN_API_KEY
export const ARBITRUM_ETHERSCAN_API_KEY = process.env.NEXT_PUBLIC_ARBITRUM_ETHERSCAN_API_KEY
export const OPTIMISM_ETHERSCAN_API_KEY = process.env.NEXT_PUBLIC_OPTIMISM_ETHERSCAN_API_KEY

export const Biconomy_AA_Key = process.env.NEXT_PUBLIC_BICONOMY_AA_KEY

export const TENDERLY_ACCESS_KEY = process.env.NEXT_PUBLIC_TENDELY_ACCESS_TOKEN
export const TENDERLY_USER = process.env.NEXT_PUBLIC_TENDERLY_USER
export const TENDERLY_PROJECT = process.env.NEXT_PUBLIC_TENDERLY_PROJECT

export const PIMLICO_API_KEY = process.env.NEXT_PUBLUC_PIMLICO_API_KEY
